name: Supabase Heartbeat

on:
  schedule:
    # Cron in GitHub Actions è in UTC e gira sul default branch
    - cron: "0 7 * * 1,5"  # Lun e Ven alle 07:00 UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call Edge Function
        env:
          HEARTBEAT_URL: ${{ secrets.HEARTBEAT_URL }}
          HEARTBEAT_SECRET: ${{ secrets.HEARTBEAT_SECRET }}
        run: |
          set -euo pipefail
          code=$(curl -sS -o /dev/null -w "%{http_code}" \
            -H "x-heartbeat-secret: $HEARTBEAT_SECRET" \
            "$HEARTBEAT_URL")
          echo "HTTP $code"
          test "$code" = "200"

